name: Android CI

on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    
    - name: Build debug.apk
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
        
    - name : upload apk
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: HMCLPE/build/outputs/apk/release/*
